### ISSUE TITLE
Increase PHP upload size limit by default

### ISSUE THREAD

**Issue by fredrikekelund** [vagrantpress/vagrantpress#112]
I've worked with the WordPress importer on my vagrantpress box quite a bit, and something I've found myself doing repeatedly is changing the upload file size limit by hand. Would be cool if that could be done by default and be something fairly high (like maybe 200M).

Here's an [SO suggestion](http://stackoverflow.com/a/12116620/618739) on how to accomplish it.

**Comment by akeif** [comment]
I can fix that for you @fredrikekelund.

I'll take a look in the next few days.

**Comment by fredrikekelund** [comment]
Cool, thanks a bunch!
