### ISSUE TITLE
PHP not executing

### ISSUE THREAD

**Issue by socki03** [vagrantpress/vagrantpress#121]
I hadn't cloned a new version of the repo in a while, but I just tried getting the latest version up and running, and every time, with a clean install, PHP wasn't being executed, just read in as text.

Went back to the last commit in January ([1998c99](https://github.com/vagrantpress/vagrantpress/commit/1998c992326fa6d593746ce4e1993eb957026eca)), cloned, installed, and it ran just fine.

**Comment by vladiiancu** [comment]
I second this.

**Comment by battlemidget** [comment]
@akeif could this be a result from your recent modifications?

**Comment by akeif** [comment]
@battlemidget Yes. It's not executing in Apache. And I'm fixing it ATM. Patch coming really soon.

**Comment by akeif** [comment]
Look like running WP unit tests successfully wasn't enough :P Should have tried to run the site through apache he.

**Comment by battlemidget** [comment]
@akeif awesome, thanks for the quick reply

**Comment by battlemidget** [comment]
@socki03 @vladiiancu can you test the PR #122

**Comment by akeif** [comment]
@battlemidget I asked a colleague to test it out.
