### ISSUE TITLE
Can no longer Remote Connect to SQL

### ISSUE THREAD

**Issue by superpowered** [vagrantpress/vagrantpress#127]
Hello,

The last few vagrantpress boxes I've put up I haven't been able to access the SQL database through Sequel Pro.

All of my older vagrantpress boxes however, still connect through Sequel Pro just fine using the same credentials

I've generally been connecting via the "SSH" option:
MySQL Host: 127.0.01
Username: wordpress
Password: wordpress
Database: 
Port:
SSH Host: 192.168.50.4
SSH User: vagrant
SSH Password: vagrant
SSH Port: 
Connect using SSL : false

<img width="475" alt="screen shot 2017-01-11 at 12 38 09 pm" src="https://cloud.githubusercontent.com/assets/7035467/21861538/ddb13af8-d7fa-11e6-9d6e-82f466fff0f2.png">
-------------------------

It's been shooting out this error recently instead:
`    

    Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o
    ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no -o 
    ServerAliveInterval=60 -o ServerAliveCountMax=1 vagrant@192.168.50.46 -L 52741:127.0.0.1:3306

    OpenSSH_6.9p1, LibreSSL 2.1.8
    debug1: Reading configuration data /etc/ssh/ssh_config
    debug1: /etc/ssh/ssh_config line 20: Applying options for *
    debug1: /etc/ssh/ssh_config line 102: Applying options for *
    debug1: Control socket " none" does not exist
    debug1: Connecting to 192.168.50.4[192.168.50.4] port 22.
    debug1: fd 3 clearing O_NONBLOCK
    debug1: Connection established.
    debug1: identity file /Users/andrew/.ssh/id_rsa type 1
    debug1: key_load_public: No such file or directory
    debug1: identity file /Users/andrew/.ssh/id_rsa-cert type -1
    debug1: key_load_public: No such file or directory
    debug1: identity file /Users/andrew/.ssh/id_dsa type -1
    debug1: key_load_public: No such file or directory
    debug1: identity file /Users/andrew/.ssh/id_dsa-cert type -1
    debug1: key_load_public: No such file or directory
    debug1: identity file /Users/andrew/.ssh/id_ecdsa type -1
    debug1: key_load_public: No such file or directory
    debug1: identity file /Users/andrew/.ssh/id_ecdsa-cert type -1
    debug1: key_load_public: No such file or directory
    debug1: identity file /Users/andrew/.ssh/id_ed25519 type -1
    debug1: key_load_public: No such file or directory
    debug1: identity file /Users/andrew/.ssh/id_ed25519-cert type -1
    debug1: Enabling compatibility mode for protocol 2.0
    debug1: Local version string SSH-2.0-OpenSSH_6.9
    debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
    debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2 pat OpenSSH_6.6.1* compat 0x04000000
    debug1: Authenticating to 192.168.50.4:22 as 'vagrant'
    debug1: SSH2_MSG_KEXINIT sent
    debug1: SSH2_MSG_KEXINIT received
    debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
    debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
    debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
    debug1: Server host key: ecdsa-sha2-nistp256
    SHA256:1u0e04xYin0faYSAX7x3ZS82JvxLapecFdsbyVLVVOE
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
    Someone could be eavesdropping on you right now (man-in-the-middle attack)!
    It is also possible that a host key has just been changed.
    The fingerprint for the ECDSA key sent by the remote host is
    SHA256:1u0e04xYin0faYSAX7x3ZS82JvxLapecFdsbyVLVVOE.
    Please contact your system administrator.
    Add correct host key in /Users/andrew/.ssh/known_hosts to get rid of this message.
    Offending ECDSA key in /Users/andrew/.ssh/known_hosts:11
    ECDSA host key for 192.168.50.4 has changed and you have requested strict checking.
    Host key verification failed.
`

**Comment by adam-stokes** [comment]
Usually an indication that there is some IP mismatching somewhere. Your known hosts file could already contain a different signature for this IP too and will need to be cleaned out

**Comment by superpowered** [comment]
That was totally it, I must have reused the IP and forgot to document it at some point. Thanks!
