### ISSUE TITLE
Is vagrantpress dreadfully slow for you?

### ISSUE THREAD

**Issue by dskvr** [vagrantpress/vagrantpress#130]
Does VagrantPress crash anytime you're doing something other than loading the homepage or single post?
Have you typed `vagrant halt` and then `vagrant up` 20 times daily just trying to get a page to load?
Are you spending 30 minutes debugging a 1 minute task 100 times?
Do you have enough time between page reloads to brew a cup of coffee?

**Try VVV or wp-vagrant instead.** Don't be like me and throw days of your life away with vagrantpress. It's a known issue that's addressed in VVV, and for whatever reason wp-vagrant is faster.

**Comment by adam-stokes** [comment]
This is for bug reporting only, not an advertising medium for your project. Please do not post this again.
