### ISSUE TITLE
How do I use wp cli?

### ISSUE THREAD

**Issue by mortona42** [vagrantpress/vagrantpress#50]
I'm a WP n00b (Switching from Drupal), and tried using the wp command [wp plugin install PLUGIN], but getting "wp: command not found"

I see mentions of wp-cli being installed, but how do I use it?

**Comment by akeif** [comment]
@battlemidget Was this done? I can take care of it no problem. Got the puppet script ready in another project.

**Comment by battlemidget** [comment]
@akeif we would love to still have this done, it would be highly appreciated if you have the time!

**Comment by akeif** [comment]
@battlemidget All right! It will be done in the next 48 hours.

**Comment by battlemidget** [comment]
@akeif perfect just mention me in the next couple of days when youre ready and ill get it merged
